# Generated by Django 5.1.4 on 2025-07-14 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDataLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_id', models.CharField(max_length=255)),
                ('element_name', models.CharField(max_length=255)),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=8)),
                ('aggregation_type', models.CharField(max_length=255)),
                ('no_of_records', models.CharField(max_length=255)),
                ('anomaly_ranges', models.CharField(max_length=255)),
                ('machine', models.CharField(max_length=255)),
                ('org_id', models.CharField(max_length=255)),
                ('time_stamp', models.CharField(max_length=255)),
                ('new_anamoly', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('error_category', models.CharField(max_length=255)),
                ('error_text', models.TextField()),
                ('severity', models.IntegerField(help_text='severity must be between 1 to 10 ( integer ) ', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('model_path', models.CharField(max_length=255)),
                ('model_created', models.BooleanField()),
                ('remarks', models.TextField()),
                ('log_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorDataLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_id', models.CharField(max_length=255)),
                ('max', models.DecimalField(decimal_places=4, max_digits=8)),
                ('min', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg', models.DecimalField(decimal_places=4, max_digits=8)),
                ('rec_train_data', models.BooleanField(default=False)),
                ('no_of_records', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('org_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255)),
                ('element_name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('server_ip', models.CharField(max_length=255)),
                ('machine_code', models.CharField(max_length=255)),
                ('element_type', models.CharField(max_length=255)),
                ('model_path', models.CharField(default='model not created', max_length=255)),
                ('upper_anamoly_limit', models.CharField(default='model not created', max_length=255)),
                ('lower_anamoly_limit', models.CharField(default='model not created', max_length=255)),
                ('aggregation_type', models.CharField(default='model not created', max_length=255)),
                ('rec_train_data', models.BooleanField(default=False)),
                ('remarks', models.TextField()),
                ('org_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('prediction', models.BooleanField(default=False)),
                ('train_dataset_size', models.IntegerField(default=0)),
                ('possible_prediction_nos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsEmailRecipients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('org_id', models.CharField(max_length=255)),
                ('recipient_type', models.CharField(choices=[('1', 'To'), ('2', 'CC'), ('3', 'Bcc')], default='To', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org_name', models.CharField(default='Default Org', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsOrg',
            fields=[
                ('company_code', models.CharField(max_length=255)),
                ('plant_code', models.CharField(max_length=255)),
                ('line_code', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
