# Generated by Django 5.1.4 on 2025-05-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0025_settingselement_possible_prediction_nos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalydatalog',
            old_name='new_anamoly',
            new_name='new_anomaly',
        ),
    ]
