# Generated by Django 5.1.5 on 2025-05-12 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0026_rename_new_anamoly_anomalydatalog_new_anomaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsemailrecipients',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
