# Generated by Django 5.1.5 on 2025-05-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0027_settingsemailrecipients_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsemailrecipients',
            name='org_name',
            field=models.CharField(default='Default Org', max_length=255),
        ),
    ]
