# Generated by Django 5.1.5 on 2025-05-20 09:35

import predictive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0028_settingsemailrecipients_org_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsemailrecipients',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='settingsemailrecipients',
            name='org_id',
            field=models.IntegerField(blank=True, choices=predictive.models.org_details, null=True),
        ),
    ]
