# Generated by Django 5.1.5 on 2025-05-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0029_alter_settingsemailrecipients_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsemailrecipients',
            name='org_id',
            field=models.IntegerField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
