# Generated by Django 5.1.5 on 2025-05-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0030_alter_settingsemailrecipients_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsemailrecipients',
            name='org_id',
            field=models.CharField(max_length=255),
        ),
    ]
