# Generated by Django 5.1.5 on 2025-05-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0031_alter_settingsemailrecipients_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsorg',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
