# Generated by Django 5.1.5 on 2025-06-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0032_settingsorg_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalydatalog',
            old_name='new_anomaly',
            new_name='new_anamoly',
        ),
    ]
