from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


# Utility function to fetch organization details (for dropdowns, etc.)
def org_details():
    # Get org_id, line_code, and plant_code from all organizations
    org_data = SettingsOrg.objects.all().values('org_id', 'line_code', 'plant_code')
    # Return a list of tuples (org_id, "plant_code | line_code")
    return [(org['org_id'], f"{org['plant_code']} | {org['line_code']}") for org in org_data]


# Stores raw sensor data logs (min, max, avg readings)
class SensorDataLog(models.Model):
    id = models.AutoField(primary_key=True)
    element_id = models.CharField(max_length=255)  # Foreign key-like reference to SettingsElement
    max = models.DecimalField(max_digits=8, decimal_places=4)  # Maximum value
    min = models.DecimalField(max_digits=8, decimal_places=4)  # Minimum value
    avg = models.DecimalField(max_digits=8, decimal_places=4)  # Average value
    rec_train_data = models.BooleanField(default=False)  # Used for training dataset
    no_of_records = models.IntegerField()  # Number of readings in this batch
    timestamp = models.DateTimeField()  # Log timestamp
    org_id = models.CharField(max_length=255)  # Organization ID

    def __str__(self):
        return f"{self.element_id} | Max: {self.max} | Min: {self.min} | Avg: {self.avg} | {self.timestamp}"


# Stores organization-level details (Company → Plant → Line)
class SettingsOrg(models.Model):
    company_code = models.CharField(max_length=255)
    plant_code = models.CharField(max_length=255)
    line_code = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)  # Created timestamp
    updated_at = models.DateTimeField(auto_now=True)  # Auto-updated timestamp
    org_id = models.AutoField(primary_key=True)

    def __str__(self):
        return f"{self.timestamp} | {self.plant_code} | {self.line_code} | ID: {self.org_id}"


# Stores sensor/element configuration details
class SettingsElement(models.Model):
    element_id = models.CharField(max_length=255)  # Sensor/element unique ID
    element_name = models.CharField(max_length=255)  # Name of the sensor
    tag = models.CharField(max_length=255)  # PLC/SCADA tag
    server_ip = models.CharField(max_length=255)  # IP address of data source
    machine_code = models.CharField(max_length=255)  # Machine identifier
    element_type = models.CharField(max_length=255)  # Type (Temp, Pressure, etc.)
    model_path = models.CharField(max_length=255, default='model not created')  # ML model path
    upper_anamoly_limit = models.CharField(max_length=255, default='model not created')
    lower_anamoly_limit = models.CharField(max_length=255, default='model not created')
    aggregation_type = models.CharField(max_length=255, default='model not created')  # e.g., Avg, Max, Min
    rec_train_data = models.BooleanField(default=False)  # Used for training dataset
    remarks = models.TextField()  # Notes about the sensor
    org_id = models.CharField(max_length=255)
    active = models.BooleanField(default=True)  # Status flag
    prediction = models.BooleanField(default=False)  # Enable prediction or not
    train_dataset_size = models.IntegerField(default=0)  # Size of training data
    possible_prediction_nos = models.IntegerField(default=0)  # Possible predictions available

    def __str__(self):
        return f"{self.element_id} | {self.element_name} | Type: {self.element_type} | Active: {self.active}"


# Stores error logs generated by different services
class ErrorLog(models.Model):
    id = models.AutoField(primary_key=True)
    service = models.CharField(max_length=255)  # Service where error occurred
    error_category = models.CharField(max_length=255)  # Error classification
    error_text = models.TextField()  # Full error details
    severity = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(10)],  # Range 1–10
        help_text="Severity must be between 1 and 10"
    )
    timestamp = models.DateTimeField()

    def __str__(self):
        return f"{self.service} | {self.error_category} | Severity: {self.severity} | {self.timestamp}"


# Stores logs related to ML model creation
class ModelLog(models.Model):
    id = models.AutoField(primary_key=True)
    start_time = models.DateTimeField()  # Model training start time
    model_path = models.CharField(max_length=255)  # Where model is stored
    model_created = models.BooleanField()  # Flag if model was created
    remarks = models.TextField()
    log_time = models.DateTimeField()  # Time of logging

    def __str__(self):
        return f"ModelLog #{self.id} | Created: {self.model_created} | Time: {self.log_time}"


# Stores detected anomaly logs for sensors
class AnomalyDataLog(models.Model):
    id = models.AutoField(primary_key=True)
    element_id = models.CharField(max_length=255)  # Reference to sensor
    element_name = models.CharField(max_length=255)
    current_value = models.DecimalField(max_digits=8, decimal_places=4)  # Current reading
    aggregation_type = models.CharField(max_length=255)
    no_of_records = models.CharField(max_length=255)  # Number of records in aggregation
    anomaly_ranges = models.CharField(max_length=255)  # Range string like "10 to 20"
    machine = models.CharField(max_length=255)  # Machine identifier
    org_id = models.CharField(max_length=255)
    time_stamp = models.CharField(max_length=255)  # Time as string
    new_anamoly = models.BooleanField(default=True)  # Flag for new anomaly

    def __str__(self):
        return f"{self.element_name} | Time: {self.time_stamp} | Org: {self.org_id}"

    # Lower spec limit extracted from anomaly_ranges
    @property
    def lsl(self):
        try:
            return float(self.anomaly_ranges.split("to")[0].strip())
        except Exception:
            return None

    # Higher spec limit extracted from anomaly_ranges
    @property
    def hsl(self):
        try:
            return float(self.anomaly_ranges.split("to")[1].strip())
        except Exception:
            return None


# Stores recipients for anomaly or error notification emails
class SettingsEmailRecipients(models.Model):
    recipient_options = [
        ('1', 'To'),
        ('2', 'CC'),
        ('3', 'Bcc'),
    ]

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)  # Recipient name
    email = models.EmailField(max_length=255)  # Email address
    org_id = models.CharField(max_length=255)
    recipient_type = models.CharField(max_length=255, choices=recipient_options, default='1')  # To/CC/Bcc
    status = models.BooleanField(default=False)  # Active or not
    created_at = models.DateTimeField(auto_now_add=True)
    org_name = models.CharField(max_length=255, default='Default Org')

    def __str__(self):
        return f"{self.name} | {self.email} | Type: {self.get_recipient_type_display()}"
